"""first db commit

Revision ID: 375ab1bc41aa
Revises: 
Create Date: 2022-12-18 14:21:23.167809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375ab1bc41aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
