"""ajouter lien epitype vs compagnie avec autogenerate

Revision ID: 5ba4dd9940fa
Revises: e601ea317345
Create Date: 2023-02-19 07:46:13.892618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba4dd9940fa'
down_revision = 'e601ea317345'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epitype', sa.Column('compagnie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'epitype', 'compagnie', ['compagnie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'epitype', type_='foreignkey')
    op.drop_column('epitype', 'compagnie_id')
    # ### end Alembic commands ###
