"""Added Compagnie table with relationship with users

Revision ID: 87cc5e659e57
Revises: 375ab1bc41aa
Create Date: 2022-12-26 13:00:14.929185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87cc5e659e57'
down_revision = '375ab1bc41aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compagnie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('subscription_type', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compagnie_name'), 'compagnie', ['name'], unique=True)
    op.add_column('user', sa.Column('compagnie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'compagnie', ['compagnie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'compagnie_id')
    op.drop_index(op.f('ix_compagnie_name'), table_name='compagnie')
    op.drop_table('compagnie')
    # ### end Alembic commands ###
