"""Added Fabricant table with relationship with Epi

Revision ID: a6c4f6b07d2e
Revises: 87cc5e659e57
Create Date: 2022-12-26 13:26:34.114362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c4f6b07d2e'
down_revision = '87cc5e659e57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabricant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fabricant_name'), 'fabricant', ['name'], unique=True)
    op.add_column('epi', sa.Column('fabricant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'epi', 'fabricant', ['fabricant_id'], ['id'])
    op.drop_index('ix_epitype_url_fabricant', table_name='epitype')
    op.drop_column('epitype', 'url_fabricant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epitype', sa.Column('url_fabricant', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('ix_epitype_url_fabricant', 'epitype', ['url_fabricant'], unique=False)
    op.drop_constraint(None, 'epi', type_='foreignkey')
    op.drop_column('epi', 'fabricant_id')
    op.drop_index(op.f('ix_fabricant_name'), table_name='fabricant')
    op.drop_table('fabricant')
    # ### end Alembic commands ###
