"""Removed username column in User Table

Revision ID: e05869b33a45
Revises: a6c4f6b07d2e
Create Date: 2022-12-26 13:57:03.377078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05869b33a45'
down_revision = 'a6c4f6b07d2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=24), autoincrement=False, nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
